/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as ProfilesMeRouteImport } from './app/routes/profiles/me'
import { Route as AuthRegisterRouteImport } from './app/routes/auth/register'
import { Route as AuthLoginRouteImport } from './app/routes/auth/login'

const ProfilesMeRoute = ProfilesMeRouteImport.update({
  id: '/profiles/me',
  path: '/profiles/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profiles/me': typeof ProfilesMeRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profiles/me': typeof ProfilesMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profiles/me': typeof ProfilesMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth/login' | '/auth/register' | '/profiles/me'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth/login' | '/auth/register' | '/profiles/me'
  id: '__root__' | '/auth/login' | '/auth/register' | '/profiles/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProfilesMeRoute: typeof ProfilesMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profiles/me': {
      id: '/profiles/me'
      path: '/profiles/me'
      fullPath: '/profiles/me'
      preLoaderRoute: typeof ProfilesMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProfilesMeRoute: ProfilesMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
